export const eventContent = [
    {
        id: 1,
        image: '/img/gg/1/1.jpg',
        title: 'Children Day',
        description: "Children's Day at Kingswood British College was a vibrant and joyous occasion for our students.The celebration featured exciting activities, laughter, and cherished moments that brought everyone together.This special day highlighted the enthusiasm and creativity of our students, making it truly memorable.",
        images: [
            '/img/gg/1/1.jpg',
            '/img/gg/1/2.jpg',
            '/img/gg/1/3.jpg',
            '/img/gg/1/4.jpg',
            '/img/gg/1/5.jpg',
        ],
        date: 'October 1, 2024',

    },
    {
        id: 2,
        image: '/img/gg/2/1.jpg',
        title: 'Preffects Badge Ceromoney',
        description: "Kingswood British College proudly held the Prefect Batch Ceremony, a significant event honoring our newly appointed prefects. These outstanding students have been selected for their leadership qualities and dedication to the school community. The ceremony marked the beginning of their important role in upholding the values of responsibility, integrity, and service. We are excited to see them lead and inspire their peers in the coming year.",
        images: [
            '/img/gg/2/1.jpg',
            '/img/gg/2/2.jpg',
            '/img/gg/2/3.jpg',
            '/img/gg/2/4.jpg',
            '/img/gg/2/5.jpg',
        ],
        date: 'October, 2024',
    },
    {
        id: 3,
        image: '/img/gg/3/1.jpg',
        title: 'Scouting Gr Badge ceromoney',
        description: "The Scouting GR Batch Ceremony at Kingswood British College was a momentous occasion celebrating the dedication and hard work of our Scouts. This ceremony recognized the students who have earned the prestigious GR badge, showcasing their commitment to the Scout's principles of leadership, service, and community involvement. We congratulate the new batch for their achievements and look forward to their continued growth in the Scouting movement.",
        images: [
            '/img/gg/3/1.jpg',
            '/img/gg/3/2.jpg',
            '/img/gg/3/3.jpg',
            '/img/gg/3/4.jpg',
            '/img/gg/3/5.jpg',
        ],
        date: 'October, 2024',
    },
    {
        id: 4,
        image: '/img/gg/4/1.jpg',
        title: 'Galle Trip',
        description: "The Galle trip organized by Kingswood British College was an unforgettable experience for our students. The excursion allowed them to explore the rich history and culture of Galle, visit iconic landmarks like the Galle Fort, and enjoy the beautiful coastal scenery. The trip fostered teamwork, learning, and fun, providing students with valuable insights and lasting memories. It was a wonderful opportunity for personal growth and exploration outside the classroom.",
        images: [
            '/img/gg/4/1.jpg',
            '/img/gg/4/2.jpg',
            '/img/gg/4/3.jpg',
            '/img/gg/4/4.jpg',
            '/img/gg/4/5.jpg',
        ],
        date: 'August, 2024',
    },
    {
        id: 5,
        image: '/img/gg/5/05.jpg',
        title: 'Nawam Poya Programme',
        description: "On the occasion of Nawam Poya, Kingswood British College hosted a meaningful program that celebrated the cultural and religious significance of this special day. The program included spiritual reflections, meditation, and activities that emphasized the values of peace, kindness, and mindfulness. Our students took part in various initiatives that deepened their understanding of this important day in Sri Lanka's Buddhist tradition, fostering a sense of unity and respect for cultural diversity.",
        images: [
            '/img/gg/5/01.jpg',
            '/img/gg/5/02.jpg',
            '/img/gg/5/03.jpg',
            '/img/gg/5/04.jpg',
            '/img/gg/5/05.jpg',
        ],
        date: 'February, 2024',
    },
    {
        id: 6,
        image: '/img/gg/6/1.jpg',
        title: 'Plantation Programme',
        description: "Kingswood British College proudly hosted a Plantation Program aimed at promoting environmental awareness and sustainability. Students participated in planting trees and learning about the importance of preserving nature. This hands-on initiative helped foster a sense of responsibility toward the environment and the future of our planet. The program encouraged students to take an active role in conserving nature and building a greener, healthier world.",
        images: [
            '/img/gg/6/1.jpg',
            '/img/gg/6/2.jpg',
            '/img/gg/6/3.jpg',
            '/img/gg/6/4.jpg',
            '/img/gg/6/5.jpg',
        ],
        date: '2024',
    },
    {
        id: 7,
        image: '/img/gg/7/2.jpg',
        title: 'Food Mania Event',
        description: "The Food Mania event at Kingswood British College was a delicious celebration of culinary creativity and diversity. Students showcased their cooking skills and explored a variety of cuisines, from local delights to international flavors. The event was a fantastic opportunity for students to work together, share their love for food, and enjoy a day filled with tasty treats and exciting food-related activities. It was an unforgettable experience that brought the school community closer through the joy of food.",
        images: [
            '/img/gg/7/1.jpg',
            '/img/gg/7/2.jpg',
            '/img/gg/7/3.jpg',
            '/img/gg/7/4.jpg',
            '/img/gg/7/5.jpg',
        ],
        date: '',
    },
];